### ISSUE TITLE
Broken links in README.md

### ISSUE THREAD

**Issue by andreas-bauer** [QMSTR/qmstr#250]
The following links in the `README.md` pointing to not existing pages:
- installation instructions -> `https://github.com/QMSTR/qmstr/blob/master/doc/Installation.md`
- Getting started -> `https://github.com/QMSTR/qmstr/blob/master/doc/Getting-Started.md`

**Comment by mirkoboehm** [comment]
Thanks for reporting! We are working on publishing the documentation to the QMSTR web site automatically, so things are being moved around at the moment. In the meantime, you can find the docs here: https://github.com/QMSTR/qmstr/tree/master/doc/content (however they may move one more time).

**Comment by mirkoboehm** [comment]
@andreas-bauer The links should be fixed now. They point to the published documents on the QMSTR web site.
