### ISSUE TITLE
Implement database query for leaves

### ISSUE THREAD

**Issue by hemarkus** [QMSTR/qmstr#280]
Create a db function to retrieve all filenodes that are not derived from other filenodes.

**Comment by hemarkus** [comment]
Already exists:
https://github.com/QMSTR/qmstr/blob/99d43b889e038c454921ace02018c43c54342862/lib/go-qmstr/database/infoNode.go#L75

**Comment by GiasemiSh** [comment]
The above query does not return file nodes. It returns one data node.  The data node with the max confidenceScore. 
We need a query to return filenodes, more specifically, filenodes that are the leaves.
