### ISSUE TITLE
Make gradle plugin android compatible

### ISSUE THREAD

**Issue by hemarkus** [QMSTR/qmstr#316]
In order to create a build graph for android apps built with gradle the qmstr-gradle-plugin needs adaptation.

- [x] plugin must not apply java plugin, as this is incompatible with the android plugin.
- [x] check for java or android plugin loaded
- [x] handle either java or android project

See https://google.github.io/android-gradle-dsl/current/ for reference of the android gradle plugin.

**Comment by senaingrid** [comment]
fixed with #397
