### ISSUE TITLE
Ninka analyzer

### ISSUE THREAD

**Issue by hemarkus** [QMSTR/qmstr#325]
Bring back ninka analyzer.

When switching to modular analyzers ninka was not migrated. Implement an analyzer that uses ninka to scan sourcefiles.

**Comment by senaingrid** [comment]
I think we can close this issue right @GiasemiSh ?

**Comment by GiasemiSh** [comment]
No we don't have a ninka analyzer

**Comment by GiasemiSh** [comment]
I just saw Mirko's comment. I am closing this issue as we do not plan to create a ninka analyzer anymore.
