### ISSUE TITLE
Testsuite common_test.go fails on TestCompleteConfig

### ISSUE THREAD

**Issue by zetoph** [QMSTR/qmstr#462]
In the feature branch `feat/configEnvOverride` several configuration directives can be added as environment variables to `qmstr-master`. This requires to move the config validation function ValidateConfig() out of ReadConfig(). Most of the test cases in **config_test.go** have been adapted to this change but one of them still fails:
```
--- FAIL: TestCompleteConfig (0.00s)
    config_test.go:53: Analyzer trust level is 0: The Testalyzer
    config_test.go:53: Analyzer trust level is 0: The Testalyzer 2
FAIL
FAIL	github.com/QMSTR/qmstr/lib/go-qmstr/config	0.016s
```
I'm not entirely sure what functionality or behaviour is tested by this. Any feedback would be appreciated. The code segment of the test case that fails is this:
```
	masterconf, err := ReadConfigFromBytes([]byte(config))
	if err != nil {
		t.Logf("Broken config %v", err)
		t.FailNow()
	}

	for _, ana := range masterconf.Analysis {
		if ana.TrustLevel == 0 {
			t.Logf("Analyzer trust level is 0: %s", ana.Name)
			t.Fail() // <--- HERE
		}
	}

	projNode := CreateProjectNode(masterconf)
	value := projNode.GetMetaData("Vendor", "")
	if value != "Endocode" {
		t.Logf("Failed to create project node; %v not Endocode", value)
		t.Fail()
	} 
```
(I have added the log message to pinpoint the exact condition that is failing)

**Comment by GiasemiSh** [comment]
This tests that the trust level of an analyzer is set. If a user doesn't include a trust level in their yaml configuration then the default should not be 0, cause in this case this analyzer's result will never be used.
That's why in ValidateConfig we include this piece of code. 

``
if analyzer.TrustLevel == 0 {
			analyzer.TrustLevel = 1
		}
``

And you removed this functionality from readConfig.

**Comment by zetoph** [comment]
Ah ok, thanks, got it now!
