### ISSUE TITLE
Use a custom output format on Scancode

### ISSUE THREAD

**Issue by GiasemiSh** [QMSTR/qmstr#464]
Currently, scancode analyzer uses the default json output from scancode.

This requires further processing/parsing on the go side to bring the data in the format required by the protobuf spec. The main issue with that is that it's done by iterating through the parsed file list for each fileNode received from the master service.

Using the path as a key in the custom structure we can reduce the computational complexity by using a map-key access with the fileNode's path.

Also it allows us to create a go structure that conforms both to
the custom output and the protobuf specs.

REF:

Scancode custom output: https://scancode-toolkit.readthedocs.io/en/latest/tutorials/how_to_format_scan_output.html#custom-output-format
Jinja2 docs: https://jinja.palletsprojects.com/en/2.11.x/U

**Comment by pombredanne** [comment]
I maintain scancode... do not hesitate to reach out if I can help!

**Comment by fullsushidev** [comment]
> Since `--custom-output` option is a less traveled area and we are missing some information from the default function, we will not use the `--custom-output` option for now.

https://github.com/QMSTR/qmstr/pull/471#issuecomment-640592050
