### ISSUE TITLE
Make Github Actions only push one image version

### ISSUE THREAD

**Issue by zetoph** [QMSTR/qmstr#480]
Currently the github actions workflow builds the qmstr-master image for the three go-versions 1.12, 1.13 and 1.14. This helps to determine compatibility issues early on, especially or version upgrades with breaking changes.
However the github action that is used in the CI (https://github.com/elgohr/Publish-Docker-Github-Action) always pushes built images to a registry, which we don't necessarily want or need for the versions 1.13 and 1.14.
We should either a) fork and modify the referenced action so that it allow for a build without push or b) find another (or possibly two) github action(s) that handle the build and push task separately or c) create an action ourselves that satisfies our requirements.

**Comment by GiasemiSh** [comment]
This is done right? @myrtosh @zetoph
