### ISSUE TITLE
Remove XML namespace annotation from modified pom.xml

### ISSUE THREAD

**Issue by zetoph** [QMSTR/qmstr#494]
The pom-patch InitContainer currently adds a default namespace (`ns0`) to the pom.xml after inserting the qmstr build plugin. This annotation is not recognizes by maven which leads to an error in the client container.

TODO: Find a way to create the modified pom.xml without the namespace annotation.

**Comment by zetoph** [comment]
https://stackoverflow.com/questions/18159221/remove-namespace-and-prefix-from-xml-in-python-using-lxml?rq=1

This seems promising

**Comment by fullsushidev** [comment]
is this task done or not? @marcomicera @zetoph

**Comment by marcomicera** [comment]
It was moved to "Done", maybe the commit is simply on another branch?
