### ISSUE TITLE
Make qmstr.yaml accessile to master

### ISSUE THREAD

**Issue by zetoph** [QMSTR/qmstr#497]
Resources:
./delpoy/base/job.yaml
./deploy/base/master-config.yaml
./deploy/base/kustomization.yaml

My guess is there is an error in the `volumeMounts` and/or `volumes` in job.yaml

NOTE: When developing with the CI I found it much easier to use kubectl commands instead of GUI.
In the Deploy to Dev step in Github Actions you can see the name of the workload/pod. Using this you can use:
```
kubectl logs -f [JOB/POD_NAME] [qmstr-client|qmstr-master|dgraph]
```

**Comment by zetoph** [comment]
Also don't forget to delete the jobs once in a while with:
```
kubectl delete jobs --all
```
;)

**Comment by fullsushidev** [comment]
related to #495

**Comment by fullsushidev** [comment]
fixed with https://github.com/QMSTR/qmstr/pull/495/commits/7b7ea38192851c5ed3b27450510991167e7086d7
