### ISSUE TITLE
Create the Fasten analyzer plugin

### ISSUE THREAD

**Issue by GiasemiSh** [QMSTR/qmstr#500]
Depends on #505 

Create a plugin on the Fasten side in java, to spin the qmstr process.

PR: https://github.com/fasten-project/fasten/pull/48

**Comment by fullsushidev** [comment]
Remaining tasks:

- [ ] Test the current PR
- [ ] Check if we need to update the entry points

**Comment by marcomicera** [comment]
Done in https://github.com/fasten-project/fasten/commit/ccd4a3c1b9c9274b0bff8f253d54dc6adb7c7b0a. Ratel ports exposed in https://github.com/fasten-project/fasten/commit/2bae39da9be98a880b8e2844626a81806614d256.

**Comment by marcomicera** [comment]
Completed in 11d6866e.

**Comment by fullsushidev** [comment]
@marcomicera this is about the https://github.com/fasten-project/fasten/pull/48 and it's not merged yet
