### ISSUE TITLE
Query to showcase the build graph

### ISSUE THREAD

**Issue by fullsushidev** [QMSTR/qmstr#512]
> As a FASTEN's Marketing Co-ordinator, I want to see the first phase of the QMSTR process: a java project build graph, so I can showcase the first version of integration between QMSTR and FASTEN.

Since we have a new demo repo to showcase the usage of QMSTR as part of FASTEN's analysis process, now we need to define a dgraph query showing from `projectNode` to `fileNodes` (including `derivedFrom` nodes).

Depends on #514

**Comment by marcomicera** [comment]
Done in https://github.com/marcomicera/fasten/commit/73e2dc717337c384615d750527a0c194d3e6c2c1.
