### ISSUE TITLE
Create a new guava demo to run QMSTR

### ISSUE THREAD

**Issue by fullsushidev** [QMSTR/qmstr#514]
> As a FASTEN's Marketing Co-ordinator, I want to see the first phase of the QMSTR process: a java project build graph, so I can showcase the first version of integration between QMSTR and FASTEN.

Since we have a new implementation of QMSTR (using k8s), now we need to create a demo repo to showcase the usage of QMSTR as part of FASTEN's analysis process.

Depends on #500, #495

**Comment by marcomicera** [comment]
Done in https://github.com/fasten-project/fasten/pull/65.

**Comment by marcomicera** [comment]
Something along the lines of https://github.com/fasten-project/fasten/pull/65.

**Comment by marcomicera** [comment]
> Something along the lines of [fasten-project/fasten#65](https://github.com/fasten-project/fasten/pull/65).

...which has now become https://github.com/fasten-project/fasten/pull/48.
