### ISSUE TITLE
Github actions to showcase java guava demo

### ISSUE THREAD

**Issue by fullsushidev** [QMSTR/qmstr#521]
> As a FASTEN's Marketing Co-ordinator, I want to see the first phase of the QMSTR process: a java project build graph, so I can showcase the first version of integration between QMSTR and FASTEN.

We have a new demo repo for java guava project and in order to present it as part of the first version of integration between QMSTR and FASTEN we need to create a Github action showcase the complete demo setup and running process.

Depends on #514

**Comment by marcomicera** [comment]
As we discussed, this really doesn't make much sense. Can we close it?
