### ISSUE TITLE
Cloning fails for repos using other default branch names than "master"

### ISSUE THREAD

**Issue by marcomicera** [QMSTR/qmstr#533]
**Describe the bug**
[`endocode/qmstr:feature/self-contained-modules`](https://github.com/endocode/qmstr/tree/feature/self-contained-modules) uses [git-sync](https://github.com/kubernetes/git-sync) to clone the repository.
However, when trying to clone a repository not using `master` as the default branch name, it fails (https://github.com/kubernetes/git-sync/issues/286).

**To Reproduce**
See https://github.com/kubernetes/git-sync/issues/286.

**Expected behavior**
It should clone the default branch regardless of its name.

**Comment by fullsushidev** [comment]
done https://github.com/QMSTR/qmstr/pull/532/commits/45c19bd643a8899af2b9f9975f8610a1ca66a22d
