### ISSUE TITLE
Create Kafka Topic input/output format

### ISSUE THREAD

**Issue by fullsushidev** [QMSTR/qmstr#534]
In order to save the information collected by QMSTR into FASTEN's metadata database, we need to create our Kafka topic input/output and document it into FASTEN's wiki following their guideline.

https://github.com/fasten-project/fasten/wiki/Kafka-Topics

**Comment by marcomicera** [comment]
Resources: [API endpoints](https://github.com/fasten-project/fasten/blob/kbapi/analyzer/restapi-plugin/design/response_codes.md) (our concern is response bodies), [KB E-R diagram](https://user-images.githubusercontent.com/8766163/93773151-06b68780-fc20-11ea-8a9e-8166ee80dfc6.png).

**Comment by marcomicera** [comment]
One Kafka topic for each “metadata” field in the KB schema.
In bold, the ones that we’re probably gonna generate:
- Package
- Dependencies
- **Package versions**
- Modules
- Binary modules
- Edges
- Callables
- **Files**

**Comment by marcomicera** [comment]
We need to query both InfoNodes and DataNodes from DGraph.

**Comment by fullsushidev** [comment]
Done with https://github.com/endocode/qmstr/commit/fc07e81fc95b34c7f6c7f8e2a25046a3509ce614 and https://github.com/endocode/qmstr/commit/2c1682f4abec9d9dce8d237cf3d2019e8dedd783
at https://github.com/endocode/qmstr/tree/fasten_reporter
